t=(1,2,3,4,5)
print(len(t))
print(max(t))
print(min(t))
print(sum(t))
print(t.count(3))
print(t.index(2))
print(t[-3])
print(t[1:3])
t=sum(t,2)
print(t)
a=('e','a','u','i','o')
print(sorted(a))
print(list(reversed(a)))

